changelog:
  exclude:
    labels:
      - documentation
  categories:
    - title: Kernel Features and Patches
      labels:
        kernel-feature
        kernel-patch
    - title: Auto Release
      labels:
        - auto-release
    - title: Updater Tools
      labels:
        - updater-tool
    - title: Bug Fixes
      labels: 
        - bug