name: Kernel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    container: locietta/loia-dev-base:latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        pacman -S --noconfirm pahole xmlto inetutils bc cpio
    
    - name: Prepare source code
      run: |
        git clone https://github.com/xanmod/linux.git --depth 1 linux
        pushd linux
        ../config.sh

    - name: Load version info into env
      run: |
        echo "CURRENT_VERSION=$(make kernelrelease)" | tee -a $GITHUB_ENV
        echo "RELEASED_VERSION=$(curl --silent 'https://github.com/locietta/xanmod-kernel-WSL2/releases/latest' | sed 's#.*tag/\(.*\)\".*#\1#')" | tee -a $GITHUB_ENV

    - name: Build kernel
      if: ${{ env.CURRENT_VERSION != env.RELEASED_VERSION }}
      run: |
        ../build.sh
        popd

    - name: Upload bzImage
      uses: actions/upload-artifact@v3
      if: ${{ env.CURRENT_VERSION != env.RELEASED_VERSION }}
      with:
        name: bzImage
        path: linux/arch/x86/boot/bzImage

    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ env.CURRENT_VERSION != env.RELEASED_VERSION }}
      with:
        name:  ${{ env.CURRENT_VERSION }}
        tag_name:  ${{ env.CURRENT_VERSION }}
        files: |
          linux/arch/x86/boot/bzImage
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        generate_release_notes: true