name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: locietta/loia-dev-base:latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        pacman -S --noconfirm pahole lld
    
    - name: Build kernel
      run: |
        chmod +x ./build.sh
        ./build.sh
    
    - name: Upload bzImage
      uses: actions/upload-artifact@v3
      with:
        name: bzImage
        path: linux/arch/x86/boot/bzImage
